sudo: required
services:
  -docker

 before_install:
  - docker build -t anapan1995/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anapan1995/docker-react npm run test -- --coverage